### ISSUE TITLE
Add documentation for SupportedFunctions/CrudFunctions 

### ISSUE THREAD

**Issue by riffrack** [JonPSmith/GenericServices#3]
Hi Jon

Could you please add some documentation for the CrudFunctions. Apologies, if I missed any existing documentation on this, however I couldn't find it in the enum in code or on GitHub.

It would be useful to understand what the different settings do & what dependancies they have, e.g. SetupSecondaryDataAsync.

Kind regards

**Comment by JonPSmith** [comment]
Hi @riffrack,

As you will see from the Wiki I am working through things but haven't got to the DTO part yet. I am currently working on getting the more complex example code from [this article](https://www.simple-talk.com/dotnet/asp.net/using-entity-framework-with-an-existing-database--user-interface/) into a state that I can up on git (it has paid for libraries that cannot go up). Once that code up it has most of the complex uses of GenericServices, which I can then refer to it in the documentation. That will take some time as its not my day job!

In the meantime I direct you to the actual code, which is fairly well documented. The DTO is built up from a number of classes for technical and logical reasons. That does mean you need to follow the trail to find things (or use Peek Definition in VS2013). The structure of the dto, starting at the bottom, is:

1. [EfGenericDtoBase.cs](https://github.com/JonPSmith/GenericServices/blob/master/GenericServices/Core/EfGenericDtoBase.cs) - holds anything that is not Generic, enums, bools etc.
2. EfGenericDtoBase.Generics, which is in two parts
  * [EfGenericDtoBase.Generic.Setup.cs](https://github.com/JonPSmith/GenericServices/blob/master/GenericServices/Core/EfGenericDtoBase.Generic.Setup.cs)
  * [EfGenericDtoBase.Generic.cs](https://github.com/JonPSmith/GenericServices/blob/master/GenericServices/Core/EfGenericDtoBase.Generic.cs)
3. Then the two DTOs for sync and Async
  * Sync [EfGenericDto.cs](https://github.com/JonPSmith/GenericServices/blob/master/GenericServices/Core/EfGenericDto.cs)
  * Async [EfGenericDtoAsync.cs](https://github.com/JonPSmith/GenericServices/blob/master/GenericServices/Core/EfGenericDtoAsync.cs)

One word of warning: Comments and documentation can get out of date, especially because GenericServices has been through a  lot of iterations. I try to keep them up to date but I'm not perfect on that.

**Comment by JonPSmith** [comment]
Hi @riffrack,

I have done a final push and got the documentation and a new example application out. I hope that solves your problem.

**Comment by riffrack** [comment]
Hi Jon

Thank you for updating the documentation and the code comments. What is the primary purpose of defining the CrudFunctions.List for example on a DTO?

Cheers

**Comment by JonPSmith** [comment]
Hi @riffrack,

I program defensively, i.e. I assume I will make some mistakes, especially when I come back to the code later. Therefore I try to build libraries that keep me on the straight and narrow. The `SupportedFunctions` property allows me to state what the DTO can do. It is design documentation that you know is right, because it is code that is executed.

The `SupportedFunctions` property carries two design decisions:
1. What is the DTO designed to do. If you look in the [SampleMvcWebAppComplex](https://github.com/JonPSmith/SampleMvcWebAppComplex) you see I have DTOs that range from supporting only one command up to ones that support all the commands.
2. If the DTO  supports  create or update does it need the `SetupSecondaryData` method? You must either override `SetupSecondaryData` and or set the `DoesNotNeedSetup` flag in `SupportedFunctions`.

PS. I suggest you start a new issue if you have questions as it will be easier for people to find by the title.

**Comment by JonPSmith** [comment]
Reopened so people can see the discussion.
